# Generated by Django 4.2.7 on 2023-12-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='posts.comment'),
        ),
    ]
