# Generated by Django 4.2.7 on 2023-12-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_name_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
