# Generated by Django 4.2.7 on 2023-12-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_comment_email_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='delete',
        ),
    ]
