# Generated by Django 4.2.7 on 2023-12-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_postlikes_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='replay',
            name='delete',
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
