# Generated by Django 4.2.7 on 2023-12-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_postlikes_name_remove_postlikes_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
