# Generated by Django 4.2.7 on 2023-12-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_delete_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
