# Generated by Django 4.2.7 on 2023-12-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_rename_title_post_postname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postname',
            new_name='title',
        ),
    ]
