# Generated by Django 4.2.7 on 2023-12-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replay',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replay',
            name='name',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
