# Generated by Django 4.2.7 on 2023-12-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
