# Generated by Django 4.2.7 on 2023-12-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_address_remove_user_bio_remove_user_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followunfollow',
            old_name='user_id',
            new_name='user',
        ),
    ]
