# Generated by Django 4.2.7 on 2023-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_user_profile_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userr',
            new_name='user',
        ),
    ]
